name: TEST
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare test
        run: |
          set -xe
          java --version
          test_diff_list=$( git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | \
                          fgrep srcs | \
                          awk -F '/' '{print $2}' | \
                          tr "[:lower:]" "[:upper:]" | \
                          uniq | \
                          tr '\n' ' ' )
          echo $test_diff_list
          export TEST_DIFF_LIST=$test_diff_list
      - name: Run tests
        run: make test_diff

