name: TEST
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test
        run: |
          set -xe
          test_pl_list=$( git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | \
                          fgrep srcs | \
                          awk -F '/' '{print $2}' | \
                          tr "[:lower:]" "[:upper:]" |
                          tr '\n' ' ' )
          echo $test_pl_list
          export TEST_PL_LIST=$test_pl_list
          make test_all
          

#git diff HEAD~5 --name-only | fgrep srcs | awk -F '/' '{print $2}' | tr "[:lower:]" "[:upper:]" | tr '\n' ' '
#C JAVA JS andrey@andrey-pc:~/dev/tetris-in-50-pl$ export TEST_PL_LIST=$(!!)
