name: TEST
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determinate language of implemantations with changes
        run: |
          set -xe
          echo "DIFF_PL_LIST=$( git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | \
                          fgrep srcs | \
                          awk -F '/' '{print $2}' | \
                          tr "[:lower:]" "[:upper:]" | \
                          uniq | \
                          tr '\n' ' ' )" >> $GITHUB_ENV
      - name: Run tests
        run: |
          set -xe
          # maybe TODO: split languages to github.action.matrix. Benifit - better grouping logs in CI, cons - harder porting to different CI
          make test_diff

