name: TEST
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check out repository code
      - run: |
          a=git diff --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
	  echo $a

        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
#git diff HEAD~5 --name-only | fgrep srcs | awk -F '/' '{print $2}' | tr "[:lower:]" "[:upper:]" | tr '\n' ' '
#C JAVA JS andrey@andrey-pc:~/dev/tetris-in-50-pl$ export TEST_PL_LIST=$(!!)
